### PR TITLE
Added three ports for boards using NXP Kinetis microcontrollers

### PR DESCRIPTION
**Pull request by jgrivera67**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
Thanks, that's awesome! :+1: 

We will need a bit of time to review those :)

**Comment by lambourg** [comment]
Hello,

One quick question: I suppose that the common and gnarl-common subdirectories are untouched from the standard runtime, right?

Best regards,
- Jerome

**Comment by jgrivera67** [comment]
Hi Jerome,

Correct, except that that I added the package task_stack_info
in gnarl-common.
Sorry for duplicating a lot of files. Is there a better way to avoid
duplicating
all the platform-independent code?

An easy way to find all the new files that I added would be to grep for my
name, like this:

PS> git grep German
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-gpio.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-mcg.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-osc.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-pmc.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-port.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-rcm.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-sim.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-uart.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f-wdog.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/kinetis_k64f.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/microcontroller_clocks.adb:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/microcontroller_clocks.ads:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/reset_counter.adb:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/reset_counter.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/watchdog_timer.adb:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/bsp/watchdog_timer.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/gnarl-common/task_stack_info.adb:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_frdm/gnarl-common/task_stack_info.ads:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-gpio.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-mcg.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-osc.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-pmc.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-port.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-rcm.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-sim.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-uart.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f-wdog.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/kinetis_k64f.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/microcontroller_clocks.adb:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/microcontroller_clocks.ads:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/reset_counter.adb:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/reset_counter.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/watchdog_timer.adb:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/bsp/watchdog_timer.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/gnarl-common/task_stack_info.adb:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_k64f_hexiwear/gnarl-common/task_stack_info.ads:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z-gpio.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z-mcg.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z-osc.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z-pmc.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z-port.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z-rcm.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z-sim.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z-uart.ads:--  Copyright
(c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/kinetis_kl25z.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/microcontroller_clocks.adb:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/microcontroller_clocks.ads:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/reset_counter.adb:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/reset_counter.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/watchdog_timer.adb:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/bsp/watchdog_timer.ads:--  Copyright (c)
2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/gnarl-common/task_stack_info.adb:--
 Copyright (c) 2016, German Rivera
ravenscar-sfp-kinetis_kl25z_frdm/gnarl-common/task_stack_info.ads:--
 Copyright (c) 2016, German Rivera

Thanks,

German

**Comment by lambourg** [comment]
If you look at the way the other runtimes are now organized, they all refer to the base_runtimes folder. The trick is to modify ravenscar_build.gpr, runtime_build.gpr and ada_source_path to point to this folder, relative to the runtime's folder directory.

As an example:
https://github.com/AdaCore/embedded-runtimes/blob/master/ravenscar-stm32f407disco/full/ada_source_path
https://github.com/AdaCore/embedded-runtimes/blob/master/ravenscar-stm32f407disco/runtime_build.gpr
and
https://github.com/AdaCore/embedded-runtimes/blob/master/ravenscar-stm32f407disco/ravenscar_build.gpr

This organisation of files is still work-in-progress, but I think you have the idea.

Best regards,
- Jerome

**Comment by jgrivera67** [comment]
I reworked my code as Jerome suggested, so I'm going to close this pull request an create a new one.

**Pull request closed without merging**
